// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlannerApp.Infrastructure.Persistence;

#nullable disable

namespace TravelPlannerApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TravelPlannerDbContext))]
    [Migration("20260329041635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("EndDateTimeLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItineraryId")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<decimal?>("LocationLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("LocationLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("StartDateTimeLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.EventAuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ItineraryId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("EventId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("event_audit_logs", (string)null);
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.Itinerary", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("itineraries", (string)null);
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.ItineraryMember", b =>
                {
                    b.Property<string>("ItineraryId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("UserId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AddedByUserId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("ItineraryId", "UserId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("itinerary_members", (string)null);
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.Event", b =>
                {
                    b.HasOne("TravelPlannerApp.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlannerApp.Domain.Entities.Itinerary", "Itinerary")
                        .WithMany("Events")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelPlannerApp.Domain.Entities.User", "UpdatedBy")
                        .WithMany("UpdatedEvents")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Itinerary");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.EventAuditLog", b =>
                {
                    b.HasOne("TravelPlannerApp.Domain.Entities.User", "ChangedByUser")
                        .WithMany("EventAuditLogs")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlannerApp.Domain.Entities.Itinerary", "Itinerary")
                        .WithMany()
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.Itinerary", b =>
                {
                    b.HasOne("TravelPlannerApp.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedItineraries")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.ItineraryMember", b =>
                {
                    b.HasOne("TravelPlannerApp.Domain.Entities.User", "AddedByUser")
                        .WithMany("AddedItineraryMembers")
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelPlannerApp.Domain.Entities.Itinerary", "Itinerary")
                        .WithMany("Members")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelPlannerApp.Domain.Entities.User", "User")
                        .WithMany("ItineraryMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Itinerary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.Itinerary", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TravelPlannerApp.Domain.Entities.User", b =>
                {
                    b.Navigation("AddedItineraryMembers");

                    b.Navigation("CreatedEvents");

                    b.Navigation("CreatedItineraries");

                    b.Navigation("EventAuditLogs");

                    b.Navigation("ItineraryMemberships");

                    b.Navigation("UpdatedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
