services:
  mysql:
    image: mysql:8.0.36
    container_name: travel-planner-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: travel_planner_app
    ports:
      - "3306:3306"
    volumes:
      - travel-planner-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  travel-planner-mysql-data:
